import type { YoutubeGuideCheckpoint } from './youtube-guide';

const GUIDE: YoutubeGuideCheckpoint[] = [
  {
    checkpoint: 1,
    cameraX: 0,
    marioX: 32,
    marioY: 208,
    score: 0,
    coins: 0,
    timeSeconds: 400,
    form: 'small',
    flipX: false,
    scene: { referenceFrameKey: 'ref_mar10_start_cp_01' },
  },
  {
    checkpoint: 2,
    cameraX: 0,
    marioX: 32,
    marioY: 208,
    score: 0,
    coins: 0,
    timeSeconds: 400,
    form: 'small',
    flipX: false,
    scene: { referenceFrameKey: 'ref_mar10_start_cp_02' },
  },
  {
    checkpoint: 3,
    cameraX: 0,
    marioX: 32,
    marioY: 208,
    score: 0,
    coins: 0,
    timeSeconds: 400,
    form: 'small',
    flipX: false,
    scene: { referenceFrameKey: 'ref_mar10_start_cp_03' },
  },
  {
    checkpoint: 4,
    cameraX: 0,
    marioX: 32,
    marioY: 208,
    score: 0,
    coins: 0,
    timeSeconds: 400,
    form: 'small',
    flipX: false,
    scene: { referenceFrameKey: 'ref_mar10_start_cp_04' },
  },
  {
    checkpoint: 5,
    cameraX: 0,
    marioX: 32,
    marioY: 208,
    score: 0,
    coins: 0,
    timeSeconds: 400,
    form: 'small',
    flipX: false,
    scene: { referenceFrameKey: 'ref_mar10_start_cp_05' },
  },
  {
    checkpoint: 6,
    cameraX: 0,
    marioX: 32,
    marioY: 208,
    score: 0,
    coins: 0,
    timeSeconds: 400,
    form: 'small',
    flipX: false,
    scene: { referenceFrameKey: 'ref_mar10_start_cp_06' },
  },
];

export function getMar10StartGuideCheckpoint(checkpoint: number): YoutubeGuideCheckpoint | null {
  return GUIDE.find((entry) => entry.checkpoint === checkpoint) ?? null;
}
