import type { YoutubeGuideCheckpoint } from './youtube-guide';

const GUIDE: YoutubeGuideCheckpoint[] = [
  {
    checkpoint: 1,
    cameraX: 0,
    marioX: 32,
    marioY: 208,
    score: 24600,
    coins: 1,
    timeSeconds: 398,
    form: 'small',
    flipX: false,
    scene: { referenceFrameKey: 'ref_world11_gameover_cp_01' },
  },
  {
    checkpoint: 2,
    cameraX: 0,
    marioX: 32,
    marioY: 208,
    score: 24600,
    coins: 1,
    timeSeconds: 394,
    form: 'small',
    flipX: false,
    scene: { referenceFrameKey: 'ref_world11_gameover_cp_02' },
  },
  {
    checkpoint: 3,
    cameraX: 0,
    marioX: 32,
    marioY: 208,
    score: 24600,
    coins: 1,
    timeSeconds: 390,
    form: 'small',
    flipX: false,
    scene: { referenceFrameKey: 'ref_world11_gameover_cp_03' },
  },
  {
    checkpoint: 4,
    cameraX: 0,
    marioX: 32,
    marioY: 208,
    score: 24600,
    coins: 2,
    timeSeconds: 386,
    form: 'small',
    flipX: false,
    scene: { referenceFrameKey: 'ref_world11_gameover_cp_04' },
  },
  {
    checkpoint: 5,
    cameraX: 0,
    marioX: 32,
    marioY: 208,
    score: 24800,
    coins: 3,
    timeSeconds: 381,
    form: 'small',
    flipX: false,
    scene: { referenceFrameKey: 'ref_world11_gameover_cp_05' },
  },
  {
    checkpoint: 6,
    cameraX: 0,
    marioX: 32,
    marioY: 208,
    score: 25200,
    coins: 4,
    timeSeconds: 378,
    form: 'small',
    flipX: false,
    scene: { referenceFrameKey: 'ref_world11_gameover_cp_06' },
  },
  {
    checkpoint: 7,
    cameraX: 0,
    marioX: 32,
    marioY: 208,
    score: 25800,
    coins: 5,
    timeSeconds: 376,
    form: 'small',
    flipX: false,
    scene: { referenceFrameKey: 'ref_world11_gameover_cp_07' },
  },
  {
    checkpoint: 8,
    cameraX: 0,
    marioX: 32,
    marioY: 208,
    score: 26600,
    coins: 6,
    timeSeconds: 374,
    form: 'small',
    flipX: false,
    scene: { referenceFrameKey: 'ref_world11_gameover_cp_08' },
  },
];

export function getWorld11GameoverGuideCheckpoint(checkpoint: number): YoutubeGuideCheckpoint | null {
  return GUIDE.find((entry) => entry.checkpoint === checkpoint) ?? null;
}

