#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
AUDIO_DIR="$ROOT_DIR/public/audio/smas"
mkdir -p "$AUDIO_DIR"

KH_ALBUM_BASE="https://downloads.khinsider.com/game-soundtracks/album/super-mario-all-stars-1993-snes"
SFX_PAGE="https://sounds.spriters-resource.com/snes/smassmw/asset/449142/"
SFX_BASE="https://sounds.spriters-resource.com"

require_bin() {
  local bin="$1"
  if ! command -v "$bin" >/dev/null 2>&1; then
    echo "[error] Missing required tool: $bin" >&2
    exit 1
  fi
}

require_bin curl
require_bin rg
require_bin ffmpeg
require_bin unzip

download_kh_track_mp3() {
  local track_slug="$1"
  local out_file="$2"
  if [[ -f "$out_file" ]]; then
    echo "[skip] $out_file"
    return
  fi

  local track_url="${KH_ALBUM_BASE}/${track_slug}"
  echo "[page] $track_url"
  local html
  html="$(curl -fsSL "$track_url")"
  local direct_mp3
  direct_mp3="$(printf '%s' "$html" | rg -o 'https://[^"]*vgmtreasurechest[^"]+\.mp3' | head -n 1)"
  if [[ -z "$direct_mp3" ]]; then
    echo "[error] Could not locate direct MP3 link for ${track_slug}" >&2
    exit 1
  fi

  echo "[down] $out_file"
  curl -fL "$direct_mp3" -o "$out_file"
}

convert_mp3_to_wav() {
  local in_mp3="$1"
  local out_wav="$2"
  if [[ -f "$out_wav" ]]; then
    echo "[skip] $out_wav"
    return
  fi
  ffmpeg -hide_banner -loglevel error -i "$in_mp3" -ac 1 -ar 32000 -y "$out_wav"
  echo "[make] $out_wav"
}

extract_sfx_from_zip() {
  local zip_file="$1"
  local entry_name="$2"
  local out_file="$3"
  if [[ -f "$out_file" ]]; then
    echo "[skip] $out_file"
    return
  fi
  unzip -p "$zip_file" "$entry_name" > "$out_file"
  echo "[make] $out_file"
}

download_kh_track_mp3 "04.%2520Title%2520BGM.mp3" "$AUDIO_DIR/title.mp3"
download_kh_track_mp3 "09.%2520SMB%2520-%2520Ground%2520BGM.mp3" "$AUDIO_DIR/overworld.mp3"
download_kh_track_mp3 "10.%2520SMB%2520-%2520Course%2520Clear.mp3" "$AUDIO_DIR/_tmp_clear.mp3"
download_kh_track_mp3 "13.%2520SMB%2520-%2520Player%2520Down.mp3" "$AUDIO_DIR/_tmp_die.mp3"

convert_mp3_to_wav "$AUDIO_DIR/_tmp_clear.mp3" "$AUDIO_DIR/clear.wav"
convert_mp3_to_wav "$AUDIO_DIR/_tmp_die.mp3" "$AUDIO_DIR/die.wav"
rm -f "$AUDIO_DIR/_tmp_clear.mp3" "$AUDIO_DIR/_tmp_die.mp3"

sfx_html="$(curl -fsSL "$SFX_PAGE")"
sfx_path="$(printf '%s' "$sfx_html" | rg -o '/media/assets/[0-9]+/449142\.zip\?updated=[0-9]+' | head -n 1)"
if [[ -z "$sfx_path" ]]; then
  echo "[error] Could not locate SMAS/SMW SFX zip on Sounds Resource page." >&2
  exit 1
fi

tmp_zip="$(mktemp /tmp/smas-sfx.XXXXXX.zip)"
trap 'rm -f "$tmp_zip"' EXIT
echo "[down] $SFX_BASE$sfx_path"
curl -fL "$SFX_BASE$sfx_path" -o "$tmp_zip"

extract_sfx_from_zip "$tmp_zip" "Jump.wav" "$AUDIO_DIR/jump.wav"
extract_sfx_from_zip "$tmp_zip" "Coin Collect.wav" "$AUDIO_DIR/coin.wav"
extract_sfx_from_zip "$tmp_zip" "Enemy Stomp.wav" "$AUDIO_DIR/stomp.wav"
extract_sfx_from_zip "$tmp_zip" "Player Powerup.wav" "$AUDIO_DIR/powerup.wav"
extract_sfx_from_zip "$tmp_zip" "Brick Break.wav" "$AUDIO_DIR/break.wav"
extract_sfx_from_zip "$tmp_zip" "Goal Pole.wav" "$AUDIO_DIR/flagpole.wav"
extract_sfx_from_zip "$tmp_zip" "Fireworks.wav" "$AUDIO_DIR/firework.wav"
extract_sfx_from_zip "$tmp_zip" "Select.wav" "$AUDIO_DIR/select.wav"
extract_sfx_from_zip "$tmp_zip" "Level Enter.wav" "$AUDIO_DIR/start.wav"

cat > "$AUDIO_DIR/README.txt" <<'TXT'
Audio files are auto-generated by scripts/download-audio.sh.
Current mapping:
- title.mp3      -> title screen BGM
- overworld.mp3  -> in-level BGM (SMB ground)
- jump.wav
- coin.wav
- stomp.wav
- powerup.wav
- break.wav
- flagpole.wav
- clear.wav
- die.wav
- firework.wav
- select.wav
- start.wav
- intro_start.wav (optional, extracted from mar10-start.mp4)
TXT

echo "[ok] Audio assets ready in $AUDIO_DIR"
