import type { AssetManifest } from '../core/contracts';

export const SMAS_ASSET_MANIFEST: AssetManifest = {
  entries: [
    { key: 'smas_tileset', kind: 'image', path: 'assets/smas/tileset_global_6211.png' },
    { key: 'smas_world11_full', kind: 'image', path: 'assets/smas/world_1-1_154289.png' },
    { key: 'smas_hud_font', kind: 'image', path: 'assets/smas/hud_font_132605.png' },
    { key: 'smas_items_blocks', kind: 'image', path: 'assets/smas/items_blocks_118565.png' },
    { key: 'smas_title_screens', kind: 'image', path: 'assets/smas/title_screens_132613.png' },
    { key: 'smas_game_over_screens', kind: 'image', path: 'assets/smas/game_over_time_up_51798.png' },
    { key: 'smas_npcs_ending', kind: 'image', path: 'assets/smas/npcs_ending_6206.png' },
    { key: 'smas_mario_luigi', kind: 'image', path: 'assets/smas/mario_luigi_83422.png' },
    { key: 'smas_mario_super_alt', kind: 'image', path: 'assets/smas/mario_super_alt.gif' },
    { key: 'smas_mario_fire_alt', kind: 'image', path: 'assets/smas/mario_fire_alt.gif' },
    { key: 'smas_enemies_mariouniverse', kind: 'image', path: 'assets/smas/enemies_mariouniverse.gif' },
    { key: 'smas_items_coins_mariouniverse', kind: 'image', path: 'assets/smas/items_coins_mariouniverse.png' },
    { key: 'smas_enemies', kind: 'image', path: 'assets/smas/enemies_6195.png' },
    { key: 'smas_effects', kind: 'image', path: 'assets/smas/effects_135664.png' },
    { key: 'smas_clouds_bg', kind: 'image', path: 'assets/smas/clouds_bg_6208.png' },
    { key: 'smas_hills_bg_1', kind: 'image', path: 'assets/smas/hills_bg_135312.png' },
    { key: 'smas_hills_bg_2', kind: 'image', path: 'assets/smas/hills_bg_135313.png' },
    { key: 'final_screen_bg', kind: 'image', path: 'assets/custom/finalscreen-clean.png' },
    { key: 'smas_bgm_title', kind: 'audio', path: 'audio/smas/title.mp3' },
    { key: 'smas_bgm_overworld', kind: 'audio', path: 'audio/smas/overworld.mp3' },
    { key: 'smas_sfx_jump', kind: 'audio', path: 'audio/smas/jump.wav' },
    { key: 'smas_sfx_coin', kind: 'audio', path: 'audio/smas/coin.wav' },
    { key: 'smas_sfx_stomp', kind: 'audio', path: 'audio/smas/stomp.wav' },
    { key: 'smas_sfx_powerup', kind: 'audio', path: 'audio/smas/powerup.wav' },
    { key: 'smas_sfx_break', kind: 'audio', path: 'audio/smas/break.wav' },
    { key: 'smas_sfx_die', kind: 'audio', path: 'audio/smas/die.wav' },
    { key: 'smas_sfx_flagpole', kind: 'audio', path: 'audio/smas/flagpole.wav' },
    { key: 'smas_sfx_clear', kind: 'audio', path: 'audio/smas/clear.wav' },
    { key: 'smas_sfx_firework', kind: 'audio', path: 'audio/smas/firework.wav' },
    { key: 'smas_sfx_select', kind: 'audio', path: 'audio/smas/select.wav' },
    { key: 'smas_sfx_start', kind: 'audio', path: 'audio/smas/start.wav' },
    { key: 'smas_intro_start', kind: 'audio', path: 'audio/smas/intro_start.wav' },
  ],
};
